<?php

namespace Package\Category\Providers;

use Illuminate\Support\ServiceProvider;

class CategoryServiceProvider extends ServiceProvider
{
    public function boot()
    {

    }

    public function register()
    {
//        parent::register(); // TODO: Change the autogenerated stub
    }
}
